### ISSUE TITLE
Various bug on Kali 2.0 rolling

### ISSUE THREAD

**Issue by leebaird** [urbanadventurer/WhatWeb#178]
WhatWeb - Next generation web scanner version 0.4.8-dev.

whatweb -i targets.txt --color=never --no-errors -t 255

/usr/share/whatweb/lib/tld.rb:85: warning: key "2nd_level_registration" is duplicated and overwritten on line 85
/usr/share/whatweb/lib/tld.rb:93: warning: key "2nd_level_registration" is duplicated and overwritten on line 93
/usr/share/whatweb/lib/tld.rb:95: warning: key "2nd_level_registration" is duplicated and overwritten on line 95
/usr/share/whatweb/plugins/wordpress.rb:436: warning: key "2.7-beta1" is duplicated and overwritten on line 453
/usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead.

/usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.

/usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/target.rb:197: warning: constant Target::TimeoutError is deprecated
/usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.

/usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:140:in`connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:140:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.

/usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead./usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:140:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.

/usr/share/whatweb/lib/extend-http.rb:102:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:140:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:140:in`connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:140:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:140:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:102:in`connect': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/whatweb/lib/extend-http.rb:140:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.

**Comment by urbanadventurer** [comment]
These issues are fixed. Try cloning the version of WhatWeb again.

**Comment by leebaird** [comment]
I'm opening a new ticket with the Kali dev team to upgrade the tool. 
The current version installed is 0.4.8-dev. It might help if you bumped your version number so that it would be easier to track.

**Comment by urbanadventurer** [comment]
I'm planning a version number increase soon.

**Comment by leebaird** [comment]
This issue still persists on Kali 2016.2 rolling. Please update your version number to at least 0.4.9 so that the new version can be pushed to Kali.

**Comment by urbanadventurer** [comment]
The deprecation warning issue is closed. A new version bump is coming soon.
